### ISSUE TITLE
Touchscreen Mode tap position desync on multiple monitors

### ISSUE THREAD

**Issue by Celysus** [moonlight-stream/moonlight-ios#433] opened 2020-12-02 05:45 UTC
I love the new touchscreen mode, however I noticed something as I was testing it. When connected to a computer that has multiple monitors, the touch position on my iPad was relative to the overall desktop space between both monitors despite the app only displaying one screen. I threw together an image to better illustrate the issue below:
![Rainmeter_Gq7Z933AYK](https://user-images.githubusercontent.com/11051905/100833212-58e50780-341e-11eb-94bf-f7fa4b11ac91.png)

**Comment by cgutman** [comment] 2020-12-06 02:41
This is a bug in GFE on the host.

Duplicate of https://github.com/moonlight-stream/moonlight-common-c/issues/49

**Closed by cgutman** 2020-12-06 02:41 UTC
