### ISSUE TITLE
Ps3 controller on ipad 3

### ISSUE THREAD

**Issue by nydal91** [moonlight-stream/moonlight-ios#129] opened 2015-06-08 13:06 UTC
Thanks for a wonderfull app. The ps3 controller left analog stick button and right analog stick button dosent detect by moonlight When i am gaming. A issue with the app or somethinge Else?

**Comment by dwaxemberg** [comment] 2015-06-10 05:53
Duplicate of issue #34

**Closed by dwaxemberg** 2015-06-10 05:53 UTC
Labels: duplicate
