### ISSUE TITLE
Connection Terminated Error for iOS and tvOS

### ISSUE THREAD

**Issue by bayramog** [moonlight-stream/moonlight-ios#599] opened 2023-12-15 07:10 UTC
**Describe the bug**
When I try to connect Sunshine instance from iOS and tvOS Moonlight client, they are creating Connection Terminated error. For same networks and Sunshine client. I can connect without any problem thru macOS client.
**Steps to reproduce**
No specific steps. I have a public ip for my Azure VM. All necessary ports are opened. I added sunshine instance with manual ip and port. It recognize and see the instance as running. Trying to connect and they are creating the error.

**Screenshots**
![image](https://github.com/moonlight-stream/moonlight-ios/assets/61725918/f46c9177-8e36-43aa-aff0-59e07a7db9e9)

![image](https://github.com/moonlight-stream/moonlight-ios/assets/61725918/48aa6f26-ac57-4923-8cd1-b26009925668)

![image](https://github.com/moonlight-stream/moonlight-ios/assets/61725918/b592bbc2-ba0e-4781-afa7-a6c939729b69)

**Affected games**
Not game specific issue.

**Other Moonlight clients**
- only for tvOS and iOS after their last updates. It is working on macOS client.

**Moonlight settings (please complete the following information)**
- HDR enabled. Also resolution changed and tried different ones. 
- Default settings were tried again with no success.

**Device details (please complete the following information)**
 - iOS version: 17.2 /tvOS version: 17.2
 - Device model: iPhone 15 Pro and Apple TV 4K 3rd Gen

**Server PC details (please complete the following information)**
 - OS: Windows 11 22H2
 - Sunshine version: 0.21 nightly
 - AMD GPU driver: 23 Q3
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Comment by oxkenshin** [comment] 2023-12-16 04:21
I have a similar issue for my iPad pro, but it's fine for my iPad mini 6. After I turned off the IPv6 option in sunshine, the iPad pro works again.

**Comment by bayramog** [comment] 2023-12-16 05:22
> I have a similar issue for my iPad pro, but it's fine for my iPad mini 6. After I turned off the IPv6 option in sunshine, the iPad pro works again.

I have never turned on IPv6 and it is still IPv4 for me. But again I have the issue 😞

**Comment by oxkenshin** [comment] 2023-12-16 05:34
There's a troubleshooting page in sunshine console webpage. The logs could show the error. For me it was something like "WSASendMsg() failed: 10022".

**Comment by bayramog** [comment] 2023-12-16 06:07
Yes, I got the same error. But IPv6 already closed for me. And before latest Moonlight update with same configs, it was working. Strange.

> There's a troubleshooting page in sunshine console webpage. The logs could show the error. For me it was something like "WSASendMsg() failed: 10022".

**Comment by oxkenshin** [comment] 2023-12-16 08:47
I cannot reproduce it now even when I turns the IPv6 option on. None of the options have I touched. Strange.

**Comment by bayramog** [comment] 2023-12-16 10:02
I also got new Sunshine nightly build but it doesn't solve it. I have exactly same network with my macOS and my Sunshine host at Azure VM. So all devices are trying to connect from my home network over internet to Azure network. macOS works but Apple TV and iPhone don't. Before Moonlight iOS update , I was able to connect. Nothing changed at both my home network and Azure side. Really interesting one.

**Comment by WXZhao7** [comment] 2023-12-27 16:21
Only iPadOS latest version can't connect with 10022.

**Comment by WXZhao7** [comment] 2023-12-27 16:52
> Only iPadOS latest version can't connect with 10022.

I could fix it by changing the public ip in ::ffff:ip to local IP.

**Comment by cgutman** [comment] 2023-12-31 19:55
This looks like an Apple kernel bug, but I added a workaround in https://github.com/cgutman/enet/commit/c6bb0e50118d08252eee308de8412751218442d6

This is fixed in v9.0.1 for iOS and tvOS, whichc is now live on the App Store.

**Closed by cgutman** 2023-12-31 19:55 UTC
