### ISSUE TITLE
Fetching App List Failed

### ISSUE THREAD

**Issue by siliconkibou** [moonlight-stream/moonlight-ios#185] opened 2015-11-10 17:44 UTC
Great work getting this out on the App Store! However it's currently completely broken.

I get "Fetching App List Failed - the connection to the PC has been interrupted" and can never connect. App is authorized in NVIDIA experience. Running iOS 9.1 on both iPad Mini Retina and iPhone 6s.

**Comment by cgutman** [comment] 2015-11-10 19:17
How many games do you have in GeForce Experience? Sometimes GFE's web server just starts returning error 500 for applist queries for no reason.

What version of GFE? Can you try Moonlight PC and see if you have the same issue?

**Comment by abattrick** [comment] 2015-11-10 19:18
I have 140 compatible games and I get the same error. Only through moonlight gfe hub works fine on my android shield. What's the deal it used to work

**Comment by cgutman** [comment] 2015-11-10 19:27
@abattrick can you see what happens if you sign out of GFE on your PC then pair via PIN in Shield Hub settings? I wonder if you'll see the same issue. What GFE version are you running?

**Comment by abattrick** [comment] 2015-11-10 20:16
Yeah I tried that I'm running newest beta 2.7.3

**Comment by siliconkibou** [comment] 2015-11-10 20:38
I'm running the latest 2.5.15.54 GFE with roughly around 70 games in its list.  I have also tried signing out of GFE and of course pairing via PIN.  It works on native Shield console and Shield portable and also via Moonlight on Amazon Kindle.  Just no love for iOS, presently.  I've not tried Moonlight from PC as I prefer to avoid Java installs.  Barring that it seems to work everywhere else.

**Comment by cgutman** [comment] 2015-11-10 21:08
So to clarify,

@siliconkibu It's working for you on Moonlight Android, but not iOS.

@abattrick It's not working for you on Moonlight Android or iOS. You tried pairing Shield Hub via PIN and were able to load the app list successfully in Shield Hub.

Is this correct?

**Comment by siliconkibou** [comment] 2015-11-10 21:10
Correct for me...I think @abattrick said "...works fine on android shield". It's a bit of a run-on sentence, but that's what I took from it.  I think we're essentially in the same camp - works natively, perhaps elsewhere, but definitely not on iOS.

**Comment by cgutman** [comment] 2015-11-10 21:17
It's somewhat significant if it does in fact work consistently on Moonlight Android because there's some additional retry logic for app lost retrieval that isn't present on iOS. If retrying doesn't universally solve it, we'll b probably need to change all Moonlight clients to use Web Sockets like Shield Hub.

**Comment by siliconkibou** [comment] 2015-11-10 21:51
Interesting...I know that manually retrying never yields any success, so whatever seems to be failing seems to do so consistently.  I'm open to any experimentation you might like to suggest.

**Comment by abattrick** [comment] 2015-11-10 22:03
Yes correct I'm only not able to get app list in moonlight.

**Comment by abattrick** [comment] 2015-11-10 22:10
Sorry guys I've been brief cuz I'm at work but my moonlight on android does the same thing. It does work through hub consistently but my moonlight will fail during pairing then show paired and then fails to fetch app list everytime. I have reloaded GeForce and logged out and back in and also tried reinstalling moonlight no luck

**Comment by siliconkibou** [comment] 2015-11-19 21:09
Just a quick update to advise that the problem persists on GFE 2.7.4.10.  Thanks!

**Comment by pal64mc** [comment] 2015-11-28 07:49
Same problem

**Comment by dentldir** [comment] 2015-11-30 08:56
Fwiw, I can retrieve the app list on an iPhone 6 running 8.1.3 with the latest moonlight / Nvidia drivers and GFE.  Video stalls out when streaming but the app list loads just fine with around 130 games.

**Comment by pal64mc** [comment] 2015-12-01 00:44
Fixed the problem, all shortcuts/.exe titles for the games have to have absolutely no special characters, only letters and numbers, no spaces, and it will work (even for them matey's games)

**Comment by cgutman** [comment] 2015-12-01 17:53
Spaces should be fine. What broke it for me was non-ASCII characters caused by adding a shortcut to mstsc.exe and keeping the default name. At least part of this bug is a duplicate of #189 but I think there's more to it because it worked on Android but not iOS for me, but some users report it doesn't work for either.

**Comment by pal64mc** [comment] 2015-12-25 08:52
ALRIGHT AFTER MESSING WITH THIS THING, AND LOOKING FOR ANSWERS, IT'D BE GREAT TO GET SOME KIND OF THANKS BY SUBBING MY YOUTUBE CHAN IF THATS OK, ANYWAYS HERES THE FIX:

Make sure none of these are problems:
1 What i said before.
2 Make sure your rxinput.dll are not modified in both the program files folder and x86 one
3 make sure if you have hamachi or some other kind of ethernet thing that your computer uses instead of default is disabled.
4 I think thats it, sub my chan as a thanks https://www.youtube.com/channel/UCB-Lw2xeKEoUl3ULlZDwOjg
(trying to hit 100 so i can have a custom channel link.)

**Comment by siliconkibou** [comment] 2015-12-29 17:52
Just a follow-up.  Using the OS X client (on 10.11) I pair successfully but I get the same "Fetching app list failed" message.  Any thoughts?  The majority of my games/apps (Steam, GOG, Origin, etc.) reside on a secondary drive (D: drive), but I doubt that's the issue.

**Comment by pal64mc** [comment] 2015-12-30 00:45
Alright, clean install geforce, if that doesnt work, make sure you dont
have any virtual networks/audio things like hamachi or like razer surround
sound. Make sure that both devices are on the exact same network, so if
your computer is plugged into a router, and the modem is giving out the
wireless signal, you need to have it so that each device is connected to
the same network device.

**Comment by siliconkibou** [comment] 2015-12-30 02:54
Thanks @pal64mc but clean install GFE, completely clean network (no virtual network or audio - never have had them), and network is identical (wired PC, wired Mac, or wireless iOS/Android device).  Same router, etc.  Still can't reliably connect.  Thanks for the assist tho.

**Comment by pal64mc** [comment] 2016-01-01 19:19
hm, whats it say? like is the host offlien or cant get applist

**Comment by cgutman** [comment] 2016-05-24 02:46
This is fixed in modern GFE versions.

**Closed by cgutman** 2016-05-24 02:46 UTC
