### ISSUE TITLE
Citrix X1 Mouse Support Doesn't Work With Magic Keyboard

### ISSUE THREAD

**Issue by rayvearn** [moonlight-stream/moonlight-ios#523] opened 2022-09-07 16:32 UTC
Mouse is still slow as all hell even with Citrix X1 mouse support checked wen using magic keyboard.

**Comment by rayvearn** [comment] 2022-09-07 16:35
related to this issue:

https://github.com/moonlight-stream/moonlight-ios/issues/491

**Comment by cgutman** [comment] 2023-03-05 21:33
Duplicate of #491

**Closed by cgutman** 2023-03-05 21:33 UTC
