### ISSUE TITLE
tvOS settings not saving & stuttering stream

### ISSUE THREAD

**Issue by Lucke0051** [moonlight-stream/moonlight-ios#478] opened 2021-11-30 18:02 UTC
**Describe the bug**
Whenever I go and change settings in the tvOS moonlight app, if I then quit the app, the settings are restored back to default. I am also experiencing problems with the stream itself, about every second the stream freezes audio and video for a quick time. I'm not sure if these problems are related.

**Specifications**
Apple TV 4K over WiFi 6 (cable doesn't appear to help)
PC with RTX 2070 over ethernet on same LAN as the Apple TV.
GeForce Experience version: 3.24.0.123
Driver version: 496.76
OS: Windows 11 21H2 (22000.348)
LG TV: 4K, 50 hz with HDR

**Steps to reproduce**
With quit I refer to exiting the app fully by sliding it off.

1. Open Moonlight tvOS app
2. Click Settings
3. Change settings
4. Play a game then quit the app (or quit right away, doesn't matter) (It seems that if you play a game right away without quitting the app, it will keep the settings until you quit).
5. Go and check settings
6. Settings have been restored for some reason

**Screenshots**
![IMG_1113](https://user-images.githubusercontent.com/30857678/144102269-e03f5bb5-4ac5-4f2c-a300-a63308c27478.JPEG)

**Comment by RaunoT** [comment] 2021-12-10 21:02
Same issue for me.

**Comment by felipejfc** [comment] 2022-02-06 23:34
@cgutman my PR didn't fix the settings being lost issue. In fact I'm still being affected from it

**Comment by FabiFTW** [comment] 2022-02-08 20:38
Same issues here.
Apple TV 4K 2021
RTX 3070
WiFi 6e (ethernet cable makes no difference)
Streaming on my Notebook just works fine but is unplayable on AppleTV.

**Comment by felipejfc** [comment] 2022-02-21 23:58
@cgutman I cant reproduce this anymore after building the latest master branch

**Comment by RaunoT** [comment] 2022-02-27 10:19
Seems to be fixed with latest release.

**Comment by cgutman** [comment] 2022-03-16 02:06
Good to hear. Must have been something on Apple's end then. Closing

**Closed by cgutman** 2022-03-16 02:06 UTC
