### ISSUE TITLE
Mouse speed way too slow on iPad

### ISSUE THREAD

**Issue by rayvearn** [moonlight-stream/moonlight-ios#491] opened 2022-02-08 16:14 UTC
I use the magic keyboard, and the mouse speed is insanely slow, even after changing the mouse sensitivity to 100 on windows and the iPad. Please add an option to increase it when streaming or at least an automation to max it out while you are streaming. No idea why it’s this slow, might just have to do with some iOS/iPadOS weirdness.

**Comment by ericsyj** [comment] 2022-02-28 09:51
I encountered the same situation when using the Bluetooth mouse on my iPad Pro 2021. Are there any improvements in subsequent versions?

**Comment by ooijiyoung** [comment] 2022-03-14 06:35
Same issue using Bluetooth Anywhere MX2 with iPad Air Gen 4

**Comment by basedcumrade** [comment] 2022-04-16 13:54
Same problem every time with the Magic Keyboard trackpad

**Comment by beren12** [comment] 2022-05-20 13:13
Same with the Logitech Combo trackpad. I don’t recall this issue using a Bluetooth mouse a year or 2 ago

**Comment by ashathe** [comment] 2022-08-08 11:55
Is this issue being improved? I’m still encountering the issue.

**Comment by oxkenshin** [comment] 2022-11-03 03:40
Same issue on my iPad Magic Keyboard trackpad.

**Comment by oxkenshin** [comment] 2022-11-03 03:47
I used to fixed this by change MOUSE_SPEED_DIVISOR from 2.5 to 1.0 in "Limelight/Input/ControllerSupport.m". But I am not sure if this will cause issues for other input devices other than magic keyboard trackpad. It would be good to add an option to change this.

**Comment by clock145** [comment] 2022-11-21 09:24
mark

**Comment by cgutman** [comment] 2022-11-22 01:03
I don't have the hardware to test this right now. Can someone else try the changes in #532 to confirm they address the issue?

**Comment by RacerDelux** [comment] 2022-11-22 15:53
> I don't have the hardware to test this right now. Can someone else try the changes in #532 to confirm they address the issue?

If I had a mac to build the app on =(... Were those changes committed and published already?

**Comment by rayvearn** [comment] 2022-11-29 13:48
i don't have a mac to build the app with the change :/

**Comment by lightsabata** [comment] 2023-01-25 15:02
> I don't have the hardware to test this right now. Can someone else try the changes in #532 to confirm they address the issue?

After building and testing i can confirm that it resolve the issue pretty well !

Client : iPadOS 16.2
Build with Xcode 14.2

PS: i will be a nice enhancement if it can be set manually on the client settings (horizontal scrollbar on left panel ?) since Windows and macOS hosts have not the same mouse sensitivity (via sunshine)

**Closed** 2023-02-20 22:03 UTC
