### ISSUE TITLE
Add Native iPad Screen Resolution Support w/ the 4:3 Aspect Ratio.

### ISSUE THREAD

**Issue by sachangregory** [moonlight-stream/moonlight-ios#385] opened 2019-09-22 17:06 UTC

**Comment by bobbybean** [comment] 2019-09-23 11:06
I believe this is already supported. Just ensure you have changed the resolution in nvidia properties to the native ipad resolution.

**Comment by sachangregory** [comment] 2019-09-23 20:28
Then it changes when you connect

**Comment by cgutman** [comment] 2019-09-24 02:11
Duplicate of https://github.com/moonlight-stream/moonlight-ios/issues/376

**Closed by cgutman** 2019-09-24 02:11 UTC
