### ISSUE TITLE
Freeze screen IPhone x

### ISSUE THREAD

**Issue by raynordss** [moonlight-stream/moonlight-ios#296] opened 2017-12-28 05:23 UTC
Hi,

With the iphone x after the launch of Steam or another game the image freezes, only the sound and movements of the joystick remain.
I have tried to remove and reinstall the app, my iPad pro does not encounter any problem it.
I hope you can find a solution to the problem.
Thank you for your help.

**Comment by gt2416** [comment] 2017-12-28 19:33
Hey, I have the same problem on my iPhone X. It only happens over internet, on Wi-Fi its perfect. Btw you can scale games to be ultrawide to make use of the full display on the phone.

**Comment by yoshi43** [comment] 2018-01-27 15:33
I am having the same issue on my iPhone X, but unlike gt2416 it is happening both locally and over the internet.

**Comment by cgutman** [comment] 2018-01-30 05:40
This typically indicates that your network can't keep up with the video bitrate requested. This can happen when there's a lot of motion on the screen, but the network is unable to recover from the dropped frames. Can you try lowering the bitrate slider?

**Comment by yoshi43** [comment] 2018-01-30 14:23
I typically keep my settings at 720p 30fps while lowering the bitrate slider to 2.5 Mbps. 

On my home network I am able to keep my 10.5 inch iPad Pro at 1080p 60fps at the default bitrate with no issues and my nvidia shield tablet at 4K 30fps at the default bitrate with no issues.

Over LTE and other networks I typically cycle between 1080p 30fps and 720p 30fps with no issues on the other devices while still having issues at 720/30 with 2.5 Mbps on the iPhone X.

I was also able to use moonlight under the same conditions on my iPhone 6s previously and the issue only started happening as soon as I upgraded to the iPhone X. It has happened over GFE 3.11 and 3.12

**Comment by gt2416** [comment] 2018-01-30 14:31
Theres definitely a bug with reconnecting the video stream when the quality is not good enough. 
I have since made a pfSense box and created a vpn to my network. Now geforce thinks Im playing locally and no port forwarding is needed. With this I can play at 720/60 on my LTE but at 1080 it still gets stuck. Since its on "LAN" it gets stuck only after 2-3mins and not within consistently within 30 seconds like on LTE

**Comment by edward9210** [comment] 2018-02-04 06:00
I have the same issue on my iPhone X, but it seems to happen in HEVC but not H.264. I modify the source code in 'Connection.m' which only add '_streamConfig.supportsHevc = false' in the main function, and then rebuild the project and install the moonlight app on my iPhone X. I test it for half an hour and it looks like the problem is solved.

**Comment by cgutman** [comment] 2018-03-31 18:50
I've gotten a report that iOS 11.3 fixes this issue. Can anyone else confirm?

**Comment by yoshi43** [comment] 2018-03-31 19:07
I've been running it for about 10 minutes now over LTE and 5 minutes over WiFi (Remote) it has not froze once. Before 11.3 I was lucky if I could run it for a minute without a freeze. This is all at 5.0 Mbps.

**Comment by edward9210** [comment] 2018-04-05 11:06
I've been testing it for half an hour on my iPhone X using HEVC without a freeze (1080P 60Hz 50Mbps). It looks like the problem has been fixed on iOS 11.3.

**Comment by cgutman** [comment] 2018-04-11 01:57
HEVC will be enabled for devices running iOS 11.3 and later to address this issue.

**Closed** 2018-04-11 01:57 UTC
