### ISSUE TITLE
HDR not working on tvOS

### ISSUE THREAD

**Issue by Supergamer1337** [moonlight-stream/moonlight-ios#446] opened 2021-01-10 18:56 UTC
From my testing so far, HDR does not seem to work on my Apple TV 4k. The game tested is Mass Effect Andromeda. It does not automatically switch to HDR for the stream, and neither does it work if I have HDR enabled in the Apple TV, as all the colors become pink... Streamed from a PC with a GTX 1080ti with a HDR capable monitor connected directly to it.

**Comment by ylor** [comment] 2021-02-04 16:49
Also seeing this. HDR works as expected using Moonlight on SHIELD TV streaming from same PC.

**Comment by adam-fox** [comment] 2021-05-05 01:23
Having the same problem. I’ve even tried using this with no luck: https://github.com/lyckantropen/moonlight_hdr_launcher

**Comment by ylor** [comment] 2022-01-09 19:16
Commenting to remove stale

**Comment by magcilyl** [comment] 2022-01-10 04:39
I have the same problem. HDR don't works on moonlight in Apple TV 4K.

**Comment by cgutman** [comment] 2022-02-13 21:36
This should be fixed in v8.0.0 rolling out now.

**Closed by cgutman** 2022-02-13 21:36 UTC

**Comment by felipejfc** [comment] 2022-02-22 00:01
yes! great work with the dynamic changing @cgutman. it's working great here, apart from sometimes when the computer is already with HDR on and moonlight inits the stream with SDR settings, then I basically go in display settings in the PC and turn HDR off and then on again and then moonlight realizes it and turns HDR mode on... seems to be some kind of bug somewhere because I cant reproduce this consistently yet, e.g. after doing the off/on of HDR I mentioned above if I stop the stream and then play again it will trigger HDR from the start
