### ISSUE TITLE
Still no 4:3 / custom resolution support in iOS?

### ISSUE THREAD

**Issue by arlojeremy** [moonlight-stream/moonlight-ios#255] opened 2016-10-21 06:29 UTC
About a year ago someone was asking about custom resolutions, because the iPad is a 4:3 device and so everything is letterboxed, because the only options in Moonlight are 1280x720 and 1920x1080.

The only "solution" offered was to download a much older version of Geforce Experience, and a much older version of Gamestream (which had a "native" option), which doesn't seem like much of a solution.

Is this an nVidia Gamestream limitation now as opposed to back then, something that no changes to Moonlight can compensate for? Or is it possible to update Moonlight to use 4:3 fullscreen on the ipad?

I should note that setting my computers resolution to a 4:3 resolution changes nothing, as the app changes the games on my PC to 720p or 1080p. Even doing the "stream desktop" trick listed in the wiki, it streams the desktop in the 4:3 resolution, but squished into a 1280x720 format.

Like many users from last year, I'd pay to have that support, as otherwise the app seems to work flawlessly.

Thanks.

**Comment by Ganlorth** [comment] 2016-11-04 10:32
I just came across Moonlight recently and the app is absolutely amazing except for that 1 flaw, i really hope they take this into consideration for us iPad users.

**Comment by jeffy777** [comment] 2016-11-07 04:39
Would love to see this as well.

**Comment by Aghassi** [comment] 2016-11-12 17:50
This topic has been discussed in depth https://github.com/moonlight-stream/moonlight-ios/issues/192

It is an issue that is known, and on the list as soon as a possible fix becomes available.

**Comment by Vahn84** [comment] 2017-11-06 13:37
1 year gone from when this issue was opened

Is this something that will be addressed or not?

**Comment by cgutman** [comment] 2017-11-09 06:33
Duplicate of #192

**Closed by cgutman** 2017-11-09 06:33 UTC
