### ISSUE TITLE
120hz support for iPhone 13 Pro and Pro Max

### ISSUE THREAD

**Issue by carlossantillana** [moonlight-stream/moonlight-ios#469] opened 2021-09-24 22:23 UTC
**Is your feature request related to a problem? Please describe.**
Apple just released the iPhone 13 Pro line which has 120hz screens like the iPad. However my phone only shows the 30FPS and 60FPS toggles.

**Describe the solution you'd like**
It would be great if you can add the 120FPS option like the iPads have for the iPhone 13 Pro and iPhone 13 Pro Max. Thank you

**Additional context**
![image](https://user-images.githubusercontent.com/22382373/134745459-6f5d24bf-5fb6-4d68-8212-0f93b5770bef.png)

**Comment by carlossantillana** [comment] 2021-09-24 22:38
I haven't done any iOS development But I imagine it will be adjusting the line below to add support for iphone's with higher refresh displays. Honestly looking at it i'm not sure why it doesn't work now

https://github.com/moonlight-stream/moonlight-ios/commit/736887b9451676667c43b74da632580305937bfb#diff-d792d3d901ccbf07b766baded43eec2935a3fd4ac78555daa98a8309b9ccb559R142

**Comment by cgutman** [comment] 2021-09-26 16:50
I checked this when the new iPhones were announced and it looks like it should just work with the current code. Both iOS and iPadOS storyboards have the 120 FPS option present. There just didn't exist an actual device that would cause the 120 Hz option to be enabled prior to iPhone 13.

Do you have an iPhone 13 Pro and you're not seeing the 120 Hz option?

**Comment by RobSjaras** [comment] 2021-09-27 00:46
> I checked this when the new iPhones were announced and it looks like it should just work with the current code. Both iOS and iPadOS storyboards have the 120 FPS option present. There just didn't exist an actual iPhone that would cause the 120 Hz option to be enabled prior to iPhone 13.
> 
> Do you have an iPhone 13 Pro and you're not seeing the 120 Hz option?

I have an iPhone 13 Pro Max and can confirm that there's only 30/60 FPS options available. This is with the newest version of Moonlight

**Comment by carlossantillana** [comment] 2021-09-27 01:06
I believe the reason for this might be that the iPhone 13 Pro series has adaptive refresh (ProMotion). so sometimes the phone runs at 10Hz sometimes at 60Hz and sometimes at 120Hz. where I believe the ipads always run at 120Hz
I found this doc  from Apple. 
https://developer.apple.com/documentation/quartzcore/optimizing_promotion_refresh_rates_for_iphone_13_pro_and_ipad_pro

**Comment by cgutman** [comment] 2021-10-06 03:30
Can someone with an iPhone 13 Pro try building the latest code? I added `CADisableMinimumFrameDurationOnPhone` which should unlock 120 Hz mode.

**Comment by RobSjaras** [comment] 2021-10-08 23:34
> Can someone with an iPhone 13 Pro try building the latest code? I added `CADisableMinimumFrameDurationOnPhone` which should unlock 120 Hz mode.

Aight, I just had it sideloaded on my 13 Pro Max and it all works as intended.
![IMG_0080](https://user-images.githubusercontent.com/1918121/136634491-804c5eec-274a-41ca-8567-d604a2d69b2b.png)
!

Also confirmed that 120hz was streamed when selecting the corresponding setting, this was tested this using the [UFO test](https://testufo.com).

**Comment by LexiStrix** [comment] 2021-10-08 23:55
Any chance I can get the instructions on how to do this? That would be amazing! Thank you all for finding a way to make this work!

**Comment by hxssgaa** [comment] 2021-10-09 08:39
I just replaced the original 4K resolution into 2550 * 1284 by simply searching and replacing 3840 with 2550. I also make it a fix height of 1284 for iPhone 13 Pro Max. Then I also create a custom resolution on my Windows 10 with a ghost monitor with resolution of 2550 * 1284 and refresh rate of 120. The result is simply amazing and everything works like a charm! Now I can play any games I want just on my Phone without any issues😄. This is a perfect example of how to utilise dynamic refresh rate up to 120hz for iPhone 13 pro / pro max. 

Below is a screenshot of using iPhone 13 Pro max to watch Dota TV with 120hz:
![IMG_1555](https://user-images.githubusercontent.com/3364031/136650984-b6249716-27fc-4d95-8f7e-678de993cc5d.PNG)

**Comment by cgutman** [comment] 2021-10-13 02:26
Fixed in Moonlight v7.2 which is now live on the App Store

**Closed by cgutman** 2021-10-13 02:26 UTC
