### ISSUE TITLE
Client not Authorized error on iPad

### ISSUE THREAD

**Issue by jveronese** [moonlight-stream/moonlight-ios#487] opened 2022-01-24 20:17 UTC
hello,

I have an iPad with Moonlight and a Windows desktop with GeForce Experience. Currently, when trying to connect I get an error on the iPad that says "The client is not authrorized. Certificate verification failed." Is there something I need to update to get this working?

**Comment by VoxHwa** [comment] 2022-01-25 03:15
Is your geforce experience the latest version and so is the nv driver?
![image](https://user-images.githubusercontent.com/96711835/150904390-c8bb6304-f896-442f-907a-c02ca225a8a9.png)

I have the same issue

**Comment by jveronese** [comment] 2022-01-25 14:32
Yep, same versions

**Comment by FrenchRedPaw** [comment] 2022-01-27 08:36
I have the same problem. Even when Moonlight is launched from a PC, it does not find itself. Can't connect to the same LAN from another PC. Even in a ZeroTier. Available current function wake up pc, that does nothing.

**Comment by goozlike** [comment] 2022-01-30 11:56
i have same issue on TVos moonlight app(

**Comment by VoxHwa** [comment] 2022-02-03 10:18
I just updated the nv driver,which is the latest.Same exists.

**Comment by cgutman** [comment] 2022-02-12 04:34
Duplicate of #485 (and fixed in GFE 3.25.0.84)

**Closed by cgutman** 2022-02-12 04:34 UTC
