### ISSUE TITLE
Moonlight Crashing iOS 16

### ISSUE THREAD

**Issue by mearl72** [moonlight-stream/moonlight-ios#528] opened 2022-09-28 13:57 UTC
**Describe the bug**
Ever since I've updated to iOS 16, I can't play for more than about 10 minutes without the app crashing (suddenly exits to the home screen). It feels like an out of memory error. If I try and leave the app mid game a couple minutes in, the rest of my phone is slowed down until I close the app completely by swiping it up. I usually use HDR with 4K resolution. This causes the crash to happen much quicker. When I lower the resolution down to 1080P still with HDR, the session lasts bit longer but still eventually crashes. I've also tried without HDR enabled and it crashes.

**Steps to reproduce**
No special steps, just using the app normally.

**Screenshots**
N/A

**Affected games**
I normally just open Playnite using the moonlight HDR application but have tried without HDR and it still crashes.

**Other Moonlight clients**
- Does the issue occur when using Moonlight on PC or Android?
I have a NVIDIA Shield and it doesn't happen on it.

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default?
Resolution: 1080p or 4K
Frame Rate: 60 FPS
Bitrate: default for resolution
Touch Mode: Touchscreen
Optimize Game Settings: No
Multi-Controller Mode: Auto
Play Audio on PC: No
HEVC Video: Yes
HDR: Yes
Frame Pacing Preference: Lowest Latency
Citrix X1 Mouse Support: Yes
Statistics Overlay: No

not sure what default settings were but I did turn off HDR and HEVC and it still crashed eventually.

**Device details (please complete the following information)**
 - iOS/tvOS version: iOS 16.0.2
 - Device model: iPhone 11

**Server PC details (please complete the following information)**
 - OS: Windows 11 21H2
 - GeForce Experience version: 3.26.0.131
 - Nvidia GPU driver: 516.94
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Additional context**
I had issues in iOS 15 even with what also appeared to be memory related but only if I kept switching back and forth between an app and moonlight. After about the 4th or 5th time of switching, the phone would become super slow until I closed completely out of the Moonlight app. If I didn't close out, the whole phone would do like a soft reset and take me back to the lock screen. But when I just stayed on the Moonlight app and didn't switch, it never crashed and I could play for more than an hour.

**Comment by cgutman** [comment] 2022-09-29 02:17
Duplicate of https://github.com/moonlight-stream/moonlight-ios/issues/527

**Closed by cgutman** 2022-09-29 02:17 UTC
