### ISSUE TITLE
iOS audio and input from local pc

### ISSUE THREAD

**Issue by Jackall85** [moonlight-stream/moonlight-ios#286] opened 2017-10-14 23:49 UTC
Hi, I would like to use my iPad just to stream the video from my pc on another room, and use a usb\audio extender to control the game with a wired Xbox 360 controller directly attached to the pc.

I would also like to listen to the audio directly from my pc, is it possible?

Thanks!

**Comment by cgutman** [comment] 2018-06-02 03:35
Duplicate of #232

**Closed by cgutman** 2018-06-02 03:35 UTC
