### ISSUE TITLE
0.9.1 v2 makes the touch buttons smaller

### ISSUE THREAD

**Issue by shusain93** [moonlight-stream/moonlight-ios#123] opened 2015-06-02 21:47 UTC
This isn't exatly a 'bug', but in the new version released on June 1st made all the touch buttons smaller than they should be on the iPhone 6. I'm not sure if this is a bug because my iPad is down for the count. If it's not a bug, would it be possible to instead add a segmented button (can't remeber the name of the control right now, it's some radio button all in one) with small through large options?

I'll loke into making a pull request if I can figure it out.

**Comment by dwaxemberg** [comment] 2015-06-03 06:19
The reason for this change is the assets are now scaled for different screen densities. The issue is iPhone 4s, 5, and 6 all use the same assets since they are "2x" screen densities, but they have very different screen sizes. These assets would have to be dynamically adjusted for the screen sizes to make them look good. Ultimately, the goal would be to allow the user to fully customize the on-screen controls: size, location, transparency, etc., however that requires quite a bit of work.

**Comment by benjabones** [comment] 2015-06-10 12:17
so, dwaxemburg: are the customisations you mention here on the to-do list then? im not a huge fan of mfi controllers as i like the portability of doing everything from the device, but im sure you're aware that the control placement is a little clunky at the moment!

**Comment by shusain93** [comment] 2015-06-10 15:20
@benjabones It's really really hard (probably impossible) to make an 18 part on screen controller that feels nice without blocking what's on the screen. I've just gotten used to taking a PS4 controller that I hook up to my PC and just using ControllersForAll with it. If I can get the two working at the same time (which is rare, mind you) it's perfect. But that is so hard to get working I usually just suffer through the onscreen controls

**Comment by dwaxemberg** [comment] 2015-10-17 10:29
fixed in e3a42db0072e327f2da8358ecadba106890af4f3

**Closed by dwaxemberg** 2015-10-17 10:29 UTC
