### ISSUE TITLE
Occasional video freeze, can still hear audio

### ISSUE THREAD

**Issue by b5mith** [moonlight-stream/moonlight-ios#504] opened 2022-04-12 02:50 UTC
On 5th Gen iPad Pro 12.9" (IOS 15.3.1) with latest version of Moonlight:
While streaming desktop (via mstsc.exe), the video sometimes freezes and never recovers. Audio is unaffected.
To fix, I have to swipe left and select "mstsc.exe" again.
Happens once every 15 minutes or so, possibly coinciding with wifi degradation. 
I don't have the same issue with Steam Link.

Edition	Windows 11 Pro
Version	21H2
OS build	22000.556
Experience	Windows Feature Experience Pack 1000.22000.556.0
Processor	Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz   2.81 GHz
Installed RAM	16.0 GB
GeForce RTX 2070
NVIDIA driver version 512.15

**Comment by magcilyl** [comment] 2022-04-22 08:58
It's a bug of Win11.
I run it well in Win 10, but after upgrading to Win 11,  the same thing happened as you discribed.

**Comment by cgutman** [comment] 2022-05-07 19:44
You can work around this issue by disabling hardware accelerated GPU scheduling on your host PC. It is on by default on Windows 11.

Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/27

**Closed by cgutman** 2022-05-07 19:44 UTC
