### ISSUE TITLE
HDR doesn’t work on IOS device 

### ISSUE THREAD

**Issue by linyusenzz** [moonlight-stream/moonlight-ios#460] opened 2021-05-23 08:03 UTC
I have tried moonlight on iphone 11 pro and 2021 ipad pro 12.9 ,but i can not start HDR streaming,but it's works on samsuang tab s7 + ，so how can i stream HDR on IOS device

**Comment by linyusenzz** [comment] 2021-05-23 08:05
both of 1070ti and 2070 can not  stream HDR on IOS device

**Comment by blackgold9** [comment] 2021-06-30 04:20
I found the issue. Moonlight on iOS does not have a user setting visible to enable HDR, but does have the setting internally that defaults to No. What is needed for this bug is a switch for the HDR setting, and everything should work. I imagine this is the issue on TV OS as well.

**Comment by rezimitpo** [comment] 2021-07-14 08:34
Also. ipad pro 5th / iphone 12pro / apple tv 4k don't work on HDR mode.

**Comment by MichlK** [comment] 2021-08-01 20:37
> I found the issue. Moonlight on iOS does not have a user setting visible to enable HDR, but does have the setting internally that defaults to No. What is needed for this bug is a switch for the HDR setting, and everything should work. I imagine this is the issue on TV OS as well.

@blackgold9:
You mean the "enableHdr:NO" in https://github.com/moonlight-stream/moonlight-ios/blob/d88321263f2b25aea39f6185b95dfbe630c627e0/Limelight/ViewControllers/SettingsViewController.m -> row 317?

**Comment by blackgold9** [comment] 2021-09-14 03:46
> > I found the issue. Moonlight on iOS does not have a user setting visible to enable HDR, but does have the setting internally that defaults to No. What is needed for this bug is a switch for the HDR setting, and everything should work. I imagine this is the issue on TV OS as well.
> 
> @blackgold9:
> Do you mean the "enableHdr:NO" in https://github.com/moonlight-stream/moonlight-ios/blob/d88321263f2b25aea39f6185b95dfbe630c627e0/Limelight/ViewControllers/SettingsViewController.m -> line 317?

That's the one!

**Comment by ahkamyaqeen** [comment] 2021-09-20 11:19
Does this mean someone can build the app with that line change, and HDR would work?

**Comment by blackgold9** [comment] 2021-10-05 04:27
Yes.

**Comment by jgreer013** [comment] 2021-10-16 22:58
I've created a PR with the necessary changes to add it as a UI setting for iOS:
https://github.com/moonlight-stream/moonlight-ios/pull/477

However, even when the setting is enabled, I still couldn't get it to work on my new iPad Pro with Destiny 2 on Steam. The game was definitely displaying in HDR, and looked correct on the television, but looked washed-out on the iPad.

**Comment by blackgold9** [comment] 2021-10-17 01:12
Did you use Moonlight HDR Launcher? (GitHub -
lyckantropen/moonlight_hdr_launcher: Launch anything in HDR mode using
Moonlight <https://github.com/lyckantropen/moonlight_hdr_launcher>).

For HDR to work over moonlight it has to be officially HDR supported by
GFE.

Moonlight HDR Launcher is an EXE that launches another app/launcher of your
choosing, and modifies GFE to think it is Mass Effect Andromeda.
This matters, because Andromeda is on the small list of  GFE HDR supported
games.
So, when you launch the fake Andromeda, GFE enables HDR streaming, then you
launch whatever you want in your launcher, now with high dynamic range
support.

I use it to launch playnite, then fire up whatever hdr game i want.

**Comment by jgreer013** [comment] 2021-10-19 01:44
@blackgold9 I tried that launcher, but no, that's not fixing the issue (In fact, I think the colors look even brighter and washed out than they did before oddly enough).

Seems like this is similar to the issue being experienced on the windows client:
https://github.com/moonlight-stream/moonlight-qt/issues/61

We're definitely sending an HDR image, it just seems like the iPad screen isn't interpreting it as one 🤔

**Comment by blackgold9** [comment] 2021-10-19 01:50
Oh man. When I last did this a few months ago Im fairly positive I had good
results. Let my try to reproduce it again to confirm.

**Comment by jgreer013** [comment] 2021-10-20 01:49
Oh wow, yeah it does seem to be working there. Let me see if I can get an example of Destiny 2 side-by-side to show what I'm seeing on my branch.

Btw, I'm running through the HDR launcher -> Steam Big Picture (the big picture mode itself is also incredibly bright) -> Destiny 2. Don't think it should make a difference going through steam but thought I'd bring it up.

**Comment by MichlK** [comment] 2021-10-30 06:39
@jgreer013 Maybe it depends on other factors, too: Additionally to the things mentioned above, my setup currently is an RTX2080 with GeForce Driver 461.92 in Windows 10 Pro 21H1 (actually in a VM on a Debian 10 KVM/QEMU host with the graphics card passed through to the VM -> VFIO) and the iPad Pro 12.9" 5th gen. with iOS 15.1.

**Comment by Colerock** [comment] 2022-03-19 09:25
Hi, I got the latest GFE, got the last update for moonlight on my Ipad pro 12.9. I got a lg oled cx. When I try to gamestream using moonlight launcher HHDRDR doesnt work at all. The image is overbrighten and aweful. There is no hevc 10 or main 10 showing during the stream, Just hevc. I have rtx 3080 and older cpu  i7 4790k.

When I try on my Android phone using moonlight launcher (andromeda game launch faker), I get proper hdr image and I can clearly see the difference in all hdr games being launched through the launcher and look as it should be.

-Is hdr on ios broken?
-Do I need a lindy hdmi 4k emulator to make it work even though I have my tv connected to the PC? 
-Do I need to upgrade my pc? If so, then why is it working on Android hdr devices?

**Comment by cat-my-earn** [comment] 2022-03-21 06:30
> Hi, I got the latest GFE, got the last update for moonlight on my Ipad pro 12.9. I got a lg oled cx. When I try to gamestream using moonlight launcher HDR doesnt work at all. The image is overbrighten and aweful. There is no hevc 10 or main 10 showing during the stream, Just hevc. I have rtx 3080 and older cpu i7 4790k.
> 
> When I try on my Android phone using moonlight launcher (andromeda game launch faker), I get proper hdr image and I can clearly see the difference in all hdr games being launched through the launcher and look as it should be.
> 
> -Is hdr on ios broken? -Do I need a lindy hdmi 4k emulator to make it work even though I have my tv connected to the PC? -Do I need to upgrade my pc? If so, then why is it working on Android hdr devices?

How should I use hdr in moonlight? Although the previous person provided the method, I didn't read it at all. I'm a newbie and I don't know a lot of things, I just want to play games displayed in hdr on iPad pro 12.9 and searched this page. Can you please teach me how to play hdr in moonlight?

**Comment by jgreer013** [comment] 2022-03-21 16:18
@Colerock @cat-my-earn HDR support won't be enabled in iOS until this PR gets merged:
https://github.com/moonlight-stream/moonlight-ios/pull/477

**Comment by Colerock** [comment] 2022-03-22 17:57
> @Colerock @cat-my-earn HDR support won't be enabled in iOS until this PR gets merged: #477

So you know when it will be merged? We need HDR enabled on Ipad Ios devices ASAP. Especially with a edid emulator.

Do you know a work around for this meanwhile?
Did you compile your own moonlight build with hdr enabled? Is it possible to run your app version on mine?

**Comment by blackgold9** [comment] 2022-03-22 18:35
It’s possible to compile your own build and deploy it. The problem is the
build expires and stops working after some time. I found that super
annoying.

**Comment by don17sch** [comment] 2022-03-22 19:30
> 

yes when you build a app with free dev accounts you need to resign every 7 days. If you buy a paid dev account it is once a year

**Comment by Colerock** [comment] 2022-03-23 11:40
I want to make a build with HDR enabled for iOS devices, I dont have MacOS PC/Laptop. I am not sure if this is possible without a Macbook PC.

I usually do stuff like this on a Windows PC using VCS and then extensions, libs, deps. 
Do someone have a quick guide how to build and deploy on Windows PC and if it is possible to even deploy on an Ipad?

**Comment by felipejfc** [comment] 2022-03-23 11:58
@Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.

**Comment by Colerock** [comment] 2022-03-24 10:25
> @Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.

I have the VM OS X machine running. Got Xcode 13 installed. Where in the source do I look for to force enable HDR?

**Comment by Colerock** [comment] 2022-03-26 10:37
> > > @Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.
> > 
> > 
> > I have the VM OS X machine running. Got Xcode 13 installed. Where in the source do I look for to force enable HDR?
> 
> this commit [3a77bf3](https://github.com/moonlight-stream/moonlight-ios/commit/3a77bf3e6557874aafc1f9d9774bd1f94e39cede) introduced changing display mode in ATV, may be a good place to start looking

Ok, but tried to build just a local clone of moonlight without changes. Got multiple errors about Undefined symbol. Am I missing something when building?

**Comment by don17sch** [comment] 2022-03-26 16:00
> > > > @Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.
> > > 
> > > 
> > > I have the VM OS X machine running. Got Xcode 13 installed. Where in the source do I look for to force enable HDR?
> > 
> > 
> > this commit [3a77bf3](https://github.com/moonlight-stream/moonlight-ios/commit/3a77bf3e6557874aafc1f9d9774bd1f94e39cede) introduced changing display mode in ATV, may be a good place to start looking
> 
> Ok, but tried to build just a local clone of moonlight without changes. Got multiple errors about Undefined symbol. Am I missing something when building?
> 
> Take a look into the build log file. This is probably a common error, but how do I fix it?
> 
> [Build target Moonlight_2022-03-26T11-59-52.txt](https://github.com/moonlight-stream/moonlight-ios/files/8355231/Build.target.Moonlight_2022-03-26T11-59-52.txt)

in order to enable HDR currently you need to modify line 454 of the following file
https://github.com/moonlight-stream/moonlight-ios/blob/master/Limelight/ViewControllers/SettingsViewController.m
there is no end user way to enable HDR it must be enabled in the source code. there is a pull request to fix this but it has not yet been merged

**Comment by Colerock** [comment] 2022-03-26 16:20
> > > > > @Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.
> > > > 
> > > > 
> > > > I have the VM OS X machine running. Got Xcode 13 installed. Where in the source do I look for to force enable HDR?
> > > 
> > > 
> > > this commit [3a77bf3](https://github.com/moonlight-stream/moonlight-ios/commit/3a77bf3e6557874aafc1f9d9774bd1f94e39cede) introduced changing display mode in ATV, may be a good place to start looking
> > 
> > 
> > Ok, but tried to build just a local clone of moonlight without changes. Got multiple errors about Undefined symbol. Am I missing something when building?
> > Take a look into the build log file. This is probably a common error, but how do I fix it?
> > [Build target Moonlight_2022-03-26T11-59-52.txt](https://github.com/moonlight-stream/moonlight-ios/files/8355231/Build.target.Moonlight_2022-03-26T11-59-52.txt)
> 
> in order to enable HDR currently you need to modify line 454 of the following file https://github.com/moonlight-stream/moonlight-ios/blob/master/Limelight/ViewControllers/SettingsViewController.m there is no end user way to enable HDR it must be enabled in the source code. there is a pull request to fix this but it has not yet been merged

Yes I figured that out. But I can't build the app for some reason. Everytime I clone the app from github, some files from the moonlight-common folder doesn't get copied as well. The folders reedsolomon, enet and src files are missing. Why is that?

Can I just manually download and copy them to where they need to be?

**Comment by don17sch** [comment] 2022-03-26 16:30
> > > > > > @Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.
> > > > > 
> > > > > 
> > > > > I have the VM OS X machine running. Got Xcode 13 installed. Where in the source do I look for to force enable HDR?
> > > > 
> > > > 
> > > > this commit [3a77bf3](https://github.com/moonlight-stream/moonlight-ios/commit/3a77bf3e6557874aafc1f9d9774bd1f94e39cede) introduced changing display mode in ATV, may be a good place to start looking
> > > 
> > > 
> > > Ok, but tried to build just a local clone of moonlight without changes. Got multiple errors about Undefined symbol. Am I missing something when building?
> > > Take a look into the build log file. This is probably a common error, but how do I fix it?
> > > [Build target Moonlight_2022-03-26T11-59-52.txt](https://github.com/moonlight-stream/moonlight-ios/files/8355231/Build.target.Moonlight_2022-03-26T11-59-52.txt)
> > 
> > 
> > in order to enable HDR currently you need to modify line 454 of the following file https://github.com/moonlight-stream/moonlight-ios/blob/master/Limelight/ViewControllers/SettingsViewController.m there is no end user way to enable HDR it must be enabled in the source code. there is a pull request to fix this but it has not yet been merged
> 
> Yes I figured that out. But I can't build the app for some reason. Everytime I clone the app from github, some files from the moonlight-common folder doesn't get copied as well. The folders reedsolomon, enet and src files are missing. Why is that?
> 
> Can I just manually download and copy them to where they need to be?

did you use `git clone --recursive https://github.com/moonlight-stream/moonlight-ios.git` ? if that does not work then yes you can just download the missing files and place them in the proper place

**Comment by Colerock** [comment] 2022-03-26 17:26
> > > > > > > @Colerock the only way on a windows machine is either you run a local VM with OS X (google it and you will find it) or you rent a remote OS X machine.
> > > > > > 
> > > > > > 
> > > > > > I have the VM OS X machine running. Got Xcode 13 installed. Where in the source do I look for to force enable HDR?
> > > > > 
> > > > > 
> > > > > this commit [3a77bf3](https://github.com/moonlight-stream/moonlight-ios/commit/3a77bf3e6557874aafc1f9d9774bd1f94e39cede) introduced changing display mode in ATV, may be a good place to start looking
> > > > 
> > > > 
> > > > Ok, but tried to build just a local clone of moonlight without changes. Got multiple errors about Undefined symbol. Am I missing something when building?
> > > > Take a look into the build log file. This is probably a common error, but how do I fix it?
> > > > [Build target Moonlight_2022-03-26T11-59-52.txt](https://github.com/moonlight-stream/moonlight-ios/files/8355231/Build.target.Moonlight_2022-03-26T11-59-52.txt)
> > > 
> > > 
> > > in order to enable HDR currently you need to modify line 454 of the following file https://github.com/moonlight-stream/moonlight-ios/blob/master/Limelight/ViewControllers/SettingsViewController.m there is no end user way to enable HDR it must be enabled in the source code. there is a pull request to fix this but it has not yet been merged
> > 
> > 
> > Yes I figured that out. But I can't build the app for some reason. Everytime I clone the app from github, some files from the moonlight-common folder doesn't get copied as well. The folders reedsolomon, enet and src files are missing. Why is that?
> > Can I just manually download and copy them to where they need to be?
> 
> did you use `git clone --recursive https://github.com/moonlight-stream/moonlight-ios.git` ? if that does not work then yes you can just download the missing files and place them in the proper place

YES! I finally managed to Build the Moonlight App with HDR enabled. Just tested it on my Ipad pro 12.9. On the statistics overlay on top, it says HEVC Main 10 as before it was just HEVC. So HDR now works on IPads and Iphones if you build the app yourself. The picture is no longer washed out. Using it with the Moonlight Launcher (Fake Andromeda Launcher) 

Fantastic. But we still need an merge and update of the official app.

**Comment by cgutman** [comment] 2022-03-27 18:18
Fixed by #460

**Closed by cgutman** 2022-03-27 18:18 UTC

**Comment by cgutman** [comment] 2022-03-29 02:58
v8.1.0 is live on the App Store with HDR support
